num1 = int(input("Enter the first number: "))
num2 = int(input("Enter the second number: "))
add = (f"{num1} + {num2} = {num1 + num2}")
substract = (f"{num1} - {num2} = {num1 - num2}")
multiply = (f"{num1} * {num2} = {num1 * num2}")
division = (f"{num1} / {num2} = {num1 / num2}")
print(add) 
print(substract)
print(multiply)
print(division)
